from pydantic import BaseModel
from typing import Optional
from models.case import CaseReference, VerificationResult


class CitationCard(BaseModel):
    case: CaseReference
    verification: Optional[VerificationResult] = None
    in_memo_location: str = ""


class ResearchMemo(BaseModel):
    title: str
    question: str
    summary: str
    analysis: str
    conclusion: str
    citations: list[CitationCard] = []
    confidence_score: float = 0.0
    jurisdiction_note: str = ""
    disclaimer: str = (
        "This research memo is generated by AI and is not legal advice. "
        "Always consult a qualified legal professional for legal matters."
    )
